
uvmf:
  environments:
    <design-name>:  
    
      agents:
      - name: <design-name>_<interface-name>_agent  
        type: <design-name>_<interface-name> 
        initiator_responder: <"INITIATOR" or "RESPONDER">  

      analysis_components:
      - name: <design-name>_pred
        type: <design-name>_predictor #component name (it has dedicated yaml file)
      
      #These allow the user to specify analysis exports & ports to add to the environment class, typically implemented when the block level environment is to be utilized within a larger system level UVM testbench. 
      analysis_exports: []
      analysis_ports: []

      #These allow the user to specify environment level configuration variables, configuration constraints and parameters for the environment class.
      config_constraints: []
      config_vars: []

      #Parameters specified here can be passed down into any of the instantiated agents or other analysis components.
      parameters: []
    
      scoreboards:
      - name: <design-name>_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: <design-name>_<interface-name>_transaction   # the transaction class that the scoreboard will operate on 
    
      #The subenvs entry allows the user to import other pre-generated UVMF environments, thus creating a hierarchical environment.
      #Typically this is used when importing QVIP UVMF environments or creating a system level UVMF testbench that is reusing block level UVMF environments
      subenvs: []
    
      tlm_connections:  #specify a point to point connection between ports/exports
      - driver: <design-name>_<interface-name>_agent.monitored_ap       # connection 00     
        receiver: <design-name>_pred.<design-name>_<interface-name>_agent_ae                            
      - driver: <design-name>_pred.<design-name>_sb_ap                  # connection 01
        receiver: <design-name>_sb.expected_analysis_export
      - driver: <design-name>_<interface-name>_agent.monitored_ap       # connection 02
        receiver: <design-name>_sb.actual_analysis_export
